---
sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.0.2.0
  - ANSIBLE_VERSION=2.0.1.0
  - ANSIBLE_VERSION=2.0.0.2
  - ANSIBLE_VERSION=1.9.6
  - ANSIBLE_VERSION=1.8.4
  - ANSIBLE_VERSION=1.7.2
  - ANSIBLE_VERSION=1.6.10

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install --no-binary ansible ansible; else pip install --no-binary ansible ansible==$ANSIBLE_VERSION; fi

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/test.yml -vvvv

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Test front-end
  - >
    wget http://google.com -O /dev/null -S --quiet -e use_proxy=yes -e http_proxy=127.0.0.1:8888 2>&1
    | grep -q 'tinyproxy'
    && (echo 'Availability test: pass' && exit 0)
    || (echo 'Availability test: fail' && exit 1)