---
- name: Install Tinyproxy for web access
  become: yes
  apt:
    update_cache: yes
    pkg: tinyproxy
    force: yes
    state: present

- name: Setup Tinyproxy Config file
  become: yes
  template:
    src: tinyproxy.conf.j2
    dest: /etc/tinyproxy.conf
  notify:
    - restart tinyproxy

- name: Remove SysV config file
  file:
    dest: /etc/init.d/tinyproxy
    state: absent

- name: Deploy Systemd config
  copy:
    dest: /etc/systemd/system/tinyproxy.service
    src: tinyproxy.service

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Ensure Tinyproxy is running
  become: yes
  service:
    enabled: yes
    name: tinyproxy
    state: started
  changed_when: False
